dataset:
  target: dataset.codeformer.CodeformerDataset
  params:
    # Path to the file list.
    file_list: 
    out_size: 512
    crop_type: center
    use_hflip: False
    
    blur_kernel_size: 41
    kernel_list: ['iso', 'aniso']
    kernel_prob: [0.5, 0.5]
    blur_sigma: [0.1, 12]
    downsample_range: [1, 12]
    noise_range: [0, 15]
    jpeg_range: [30, 100]

data_loader:
  batch_size: 16
  shuffle: true
  num_workers: 16
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
